version: "3"

networks:
  beersnet:
    driver: bridge

services:
  mongoapp:
    image: mongo
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - mdbdata:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - beersnet
    env_file:
      - .env
  beersapi:
    build: .
    image: beersapi:1.0
    ports:
      - ${PORT}:${PORT}
    networks:
      - beersnet
    volumes:
      - ./assets:/rest-api/beers/assets
    depends_on:
      - mongoapp

volumes:
  mdbdata:
    driver: local